# Generated by Django 3.0.5 on 2020-07-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0005_auto_20200722_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesInCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'RolesInCommunity',
            },
        ),
    ]
