# Generated by Django 3.0.5 on 2020-07-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0006_rolesincommunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('ingame_name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('pubg_id', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_no', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('total_matches_played', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_kills', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_knockout', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_damage', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('yt_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('rolesInCommunity', models.ManyToManyField(related_name='peoples_roles_in_Community', to='pubg.RolesInCommunity')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pubg.Teams')),
            ],
            options={
                'verbose_name_plural': 'Peoples',
            },
        ),
    ]
