# Generated by Django 3.0.5 on 2020-07-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0008_awards_playershistory_prize_totaltournament_tournamenttags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayersHistory',
            new_name='PeoplesHistory',
        ),
    ]
