# Generated by Django 3.0.5 on 2020-07-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0009_auto_20200723_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleshistory',
            options={'verbose_name_plural': 'PeoplesHistory'},
        ),
    ]
