# Generated by Django 3.0.5 on 2020-10-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0013_totaltournament_priorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaltournament',
            name='endings_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totaltournament',
            name='starting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
